title: OS2RPA Documentation
description: Documentation for the OS2RPA project
theme: just-the-docs

url: https://itk-dev-rpa.github.io/os2rpa-docs

aux_links:
  Template Repository: https://github.com/itk-dev-rpa/OS2RPA-docs
