title: OpenOrchestrator Documentation
description: Documentation for the OpenOrchestrator project
theme: just-the-docs

url: https://itk-dev-rpa.github.io/OpenOrchestrator-docs/

aux_links:
  Project Repository: https://github.com/itk-dev-rpa/OpenOrchestrator-docs
