on: pull_request
name: Review
jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install

      - name: markdownlint
        run: yarn check-coding-standards 